/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: is9mWQ4fxUU5CNAhHrrven

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_9CN4PaDzwqq } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 9c-N4PaDzwqq/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_9CN4PaDzwqq
});
